import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Image from 'next/image';
import Link from 'next/link';
import { FaGithubSquare } from 'react-icons/fa';
import { FaLinkedin } from 'react-icons/fa';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'My Portfolio',
  description: 'Generated by Next.js & Sanity.io',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className='min-h-screen bg-gradient-to-b from-dark from-20% to-darkblue to-90%'
    >
      <body>
        <header className='sticky top-0 m-4 rounded-lg border-b border-blue bg-dark shadow-md shadow-teal'>
          <nav className='container mx-auto'>
            <div className='flex items-center justify-between'>
              <Image
                src='/logo.png'
                alt='Charlie Ylijoki'
                width={100}
                height={50}
                className=''
              />
              <div className='items-center space-x-4 md:flex'>
                <Link
                  href='/'
                  className='rounded-lg border border-dark p-2 text-lg text-light transition hover:border-blue hover:shadow-md hover:shadow-teal'
                >
                  About
                </Link>
                <Link
                  href='/projects'
                  className='rounded-lg border border-dark p-2 text-lg text-light transition hover:border-blue hover:shadow-md hover:shadow-teal'
                >
                  Projects
                </Link>
              </div>
            </div>
          </nav>
        </header>
        <main className='m-4 py-10'>{children}</main>
        <footer className='m-4 rounded-lg bg-dark shadow-md shadow-teal'>
          <div className='container mx-auto flex flex-col items-center justify-center'>
            <div className='flex'>
              <Link
                href='https://www.linkedin.com/in/charles-ylijoki/'
                target='_blank'
                className='p-2'
              >
                <FaLinkedin
                  size={30}
                  className='rounded-md border border-light bg-light transition hover:border-blue hover:bg-blue hover:shadow-md hover:shadow-teal'
                />
              </Link>
              <Link
                href='https://github.com/ylijokic'
                target='_blank'
                className='p-2'
              >
                <FaGithubSquare
                  size={30}
                  className='rounded-md border border-light bg-light transition hover:border-blue hover:bg-blue hover:shadow-md hover:shadow-teal'
                />
              </Link>
            </div>
            <p className='text-sm text-light'>
              Created by Charlie Ylijoki, © 2023
            </p>
          </div>
        </footer>
      </body>
    </html>
  );
}
